[package]
name = "rust_hello_server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.1", features = ["multipart"] }
tokio = { version = "1.0", features = ["full"] }
hyper = "1.6.0"
